CREATE TABLE IF NOT EXISTS project_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    UNIQUE(project_id, user_id)
);

CREATE TABLE IF NOT EXISTS member_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    role_id VARCHAR(32) NOT NULL,
    granted_by VARCHAR(64) NOT NULL,
    UNIQUE(member_id, role_id)
);
